language: elixir
matrix:
  include:
    - otp_release: 21.0
      elixir: 1.7.3
    - otp_release: 20.3
      elixir: 1.7.3
    - otp_release: 21.0
      elixir: 1.6.6
    - otp_release: 20.3
      elixir: 1.6.6
    - otp_release: 19.3
      elixir: 1.6.6
sudo: false
before_script:
  - mix deps.get --only test
script:
  - mix test
after_script:
  - cd $TRAVIS_BUILD_DIR
  - mix deps.get --only dev
  - MIX_ENV=docs mix inch.report
